# Generated by Django 2.2 on 2021-03-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_authenticated',
            field=models.BooleanField(default=True, verbose_name='authenticated'),
        ),
    ]
