# Generated by Django 2.2 on 2021-03-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_person_is_authenticated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-created_at'], 'verbose_name': 'person', 'verbose_name_plural': 'persons'},
        ),
    ]
