# Generated by Django 2.2 on 2021-03-28 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20210321_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='is_admin',
            new_name='is_staff',
        ),
        migrations.AddField(
            model_name='person',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='super user'),
        ),
    ]
