# Generated by Django 2.2 on 2021-03-21 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0003_auto_20210321_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='person')),
            ],
            options={
                'verbose_name': 'task folder',
                'verbose_name_plural': 'task folders',
                'db_table': 'task_folder',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('default', models.BooleanField(default=False, verbose_name='default')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='person')),
                ('taskFolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.TaskFolder', verbose_name='task folder')),
            ],
            options={
                'verbose_name': 'task section',
                'verbose_name_plural': 'task sections',
                'db_table': 'task_section',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='memo')),
                ('is_done', models.BooleanField(default=False, verbose_name='is done')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='start date')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='due date')),
                ('is_star', models.BooleanField(default=False, verbose_name='star')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person')),
                ('taskFolder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.TaskFolder')),
                ('taskSection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.TaskSection')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
                'db_table': 'task',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('name', models.CharField(max_length=32, verbose_name='name')),
                ('is_done', models.BooleanField(default=False, verbose_name='is done')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Person', verbose_name='person')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Task', verbose_name='task')),
            ],
            options={
                'verbose_name': 'sub task',
                'verbose_name_plural': 'sub tasks',
                'db_table': 'sub_task',
                'ordering': ['-created_at'],
            },
        ),
    ]
