# Generated by Django 2.2 on 2021-05-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksection',
            name='default',
        ),
        migrations.AlterField(
            model_name='task',
            name='memo',
            field=models.TextField(blank=True, default='', verbose_name='memo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskFolder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='task.TaskFolder'),
        ),
    ]
